apiVersion: apps/v1
kind: Deployment
metadata:
  name: migrations
spec:
  replicas: 1
  selector:
    matchLabels:
      name: migrations
  template:
    metadata:
      labels:
        name: migrations
    spec:
      serviceAccountName: migrations
      containers:
        - name: migrations
          # Replace this with the built image name
          image: hth0919/migrations:v0.0.4
          command:
          - migrations
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "migrations"
