apiVersion: apps/v1
kind: Deployment
metadata:
  name: migrations
spec:
  replicas: 1
  selector:
    matchLabels:
      name: migration-rules
  template:
    metadata:
      labels:
        name: migration-rules
    spec:
      serviceAccountName: migration-rules
      containers:
        - name: migrationrule
          # Replace this with the built image name
          image: hth0919/migrationrules:v0.0.4
          command:
          - migrationrules
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "migration-rules"
