kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: migrationrules
subjects:
- kind: ServiceAccount
  name: migrationrules
  namespace: default
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: migration-rules
  apiGroup: rbac.authorization.k8s.io
